#!/bin/bash -l
# Run batch inference on a set of inputs:
#     ./batch-infer METHOD RESULTS_PREFIX [--dry-run]
# METHOD in workflow/targets/
# af3_msa_only.smk
#
LOGS_DATE=$2/.snakemake/logs/`date +"%y-%m-%d"`
RESULTS_PREFIX_ENC=`echo -n $2 | sed -e 's#/#-#g'`
JOBNAME="batch-infer:$1=$RESULTS_PREFIX_ENC"
PROFILE=`pwd`/software/smk-simple-slurm-eu

cat - <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=$JOBNAME
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=16GB
#SBATCH --tmp=16834
#SBATCH --time=1:00:00
#SBATCH --output=$LOGS_DATE/$JOBNAME-%j.txt

#load the conda environment
eval "\$(conda shell.bash hook)"
conda activate af3

#run snakemake
snakemake $1 --snakefile workflow/targets/$1.smk \\
    --configfile workflow/config/defaults.yaml $2/config.yaml \\
    --profile=$PROFILE --workflow-profile=workflow/profiles/default \\
    --directory $2 --rerun-triggers input $3
EOF
